### ISSUE TITLE
ext-php-rs 0.14 fails to build with PHP 8.4.10 (_zend_function_entry field mismatch)

### ISSUE THREAD

**Issue by TachyonConcepts** [davidcole1340/ext-php-rs#545]
## Description
When trying to compile a project using ext-php-rs (v0.14.2) against PHP 8.4.10, the build fails with multiple errors due to missing struct fields in _zend_function_entry and type mismatches in zend_is_true.

It seems the Zend API has changed in PHP 8.4 (fields doc_comment and frameless_function_infos removed, and zend_is_true return type adjusted), while ext-php-rs is still targeting older PHP versions.

## Environment

ext-php-rs: 0.14.2

PHP: 8.4.10

Rust: 1.88.0

OS: Ubuntu 24.04

## Steps to Reproduce
1. Install PHP 8.4.10 (with headers).

2. Add ext-php-rs = "0.14" to Cargo.toml.

3. Build a minimal extension.

4. Run cargo build.

5. Compilation fails with the above errors.

**PHP Code:**
```php
<?php
```

### Actual Behavior
```
Compilation fails due to outdated bindings referencing removed fields in _zend_function_entry and type mismatches.
```

### Expected Behavior
```
The extension should compile successfully against PHP 8.4.
```

### Log Output

```shell
error[E0560]: struct `_zend_function_entry` has no field named `doc_comment`
  --> /.../ext-php-rs-0.14.2/src/builders/function.rs:62:17
   |
62 |                 doc_comment: ptr::null(),
   |                 ^^^^^^^^^^^ `_zend_function_entry` does not have this field
   = note: all struct fields are already assigned

error[E0560]: struct `_zend_function_entry` has no field named `frameless_function_infos`
  --> /.../ext-php-rs-0.14.2/src/builders/function.rs:64:17
   |
64 |                 frameless_function_infos: ptr::null(),
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^ `_zend_function_entry` does not have this field
   = note: all struct fields are already assigned

...

error[E0308]: mismatched types
   --> /.../ext-php-rs-0.14.2/src/zend/handlers.rs:257:36
    |
257 | ...                   if zend_is_true(&raw mut zv) {
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `bool`, found `i32`
```

### Affected Components

- [x] ext-php-rs
- [ ] macros
- [ ] cli (cargo-php)

### PHP Version

```plain
PHP 8.4.10 (cli) (built: Jul  3 2025 12:41:53) (NTS)
Copyright (c) The PHP Group
Built by Debian
Zend Engine v4.4.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.10, Copyright (c), by Zend Technologies
```

### `ext-php-rs` Version

0.14.2

### Operating System

Ubuntu 24.04

**Comment by Xenira** [comment]
Thanks for the report. Will have a look once I am home.

**Comment by Xenira** [comment]
Hey @TachyonConcepts I was not able to reproduce this on my end. PHP src also has those fields: https://github.com/php/php-src/blob/4647dfc9887c5d506facd4d559500193484efd1c/Zend/zend_API.h#L41-L42

Can you check if you have the `PHP` or `PHP_CONFIG` environment variable set to a different PHP version?

Seems like this is a new project but try `cargo clean`.

**Comment by Xenira** [comment]
> It seems the Zend API has changed in PHP 8.4 (fields doc_comment and frameless_function_infos removed, and zend_is_true return type adjusted), while ext-php-rs is still targeting older PHP versions.

Actually the other way around. Those are new in 8.4, thats why I think that you are somehow building using a different php verision

**Comment by TachyonConcepts** [comment]
I only have one PHP version, I just downgraded it from PHP 8.4 to PHP 8.3 and everything started working stably and smoothly. If I run into a similar issue in the future, I’ll definitely let you know! For now, many thanks for the quick feedback!

**Comment by Xenira** [comment]
We do test PHP 8.4 in our CI/CD so it should work.

Definitely let me know if you run into further issues.
